[package]
name = "diffcount"
version = "0.1.0"
authors = ["Tim Thompson <tim@wokket.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#console_error_panic_hook = "0.1.6"
stdweb = "0.4.20"
yew = "0.9.0"